
# This should be built by bomresolver, Canadian cross 
FROM alpine:3.14

# Setup alpine build environment
RUN apk --update add alpine-sdk build-base pcre-dev autoconf automake
RUN echo PACKAGER_PRIVKEY="/pki/iafw.rsa" > /etc/abuild.conf
RUN mkdir -p  /home/builder
ENV REPODEST /home/builder/packages

WORKDIR /root



