apiVersion: v1
kind: PersistentVolume
metadata:
  name: bomresolver-checkout
spec:
  storageClassName: bomresolver-checkout
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage.hq.t2data.com
    path: "/var/k8/resolver/checkout"
