---
#
# This defines the ingress rule
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sbom-resolver
  labels:
    app: sbom-resolver
  annotations:
    plugins.konghq.com: opa-kramfors
spec:
  rules:
  - host: lb.t2data.com
    http:
      paths:
      - path: /resolver/alpine/v1
        backend:
          serviceName: sbom-resolver
          servicePort: 8080


---
#
# This defines timeout
#
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations:
  name: sbom-resolver
  namespace: default
proxy:
  connect_timeout: 3000000
  protocol: http
  read_timeout: 3000000
  retries: 10
  write_timeout: 3000000
route:
  protocols:
    - http

